database:
  host: localhost
  port: 5555
  name: listener_db
  user: postgres
  password: 1

audio:
  output_dir: recordings
  default_duration_sec: 300
  sample_rate: 16000
  channels: 1
  chunk_size: 1024

server:
  host: 0.0.0.0
  port: 8080

huggingface:
  token: "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"

models:
  whisper_model: small  # base, small, medium
  diarization_model: pyannote/speaker-diarization-3.1