# review_service/Dockerfile

FROM python:3.10-slim

# Если нужны системные зависимости — добавь их
# RUN apt-get update && apt-get install -y ...

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]